### ISSUE TITLE
面板启用一段时间后访问会提示500

### ISSUE THREAD

**Issue by IllyaTheHath** [pch18-docker/baota#36]
宿主机Archlinux环境，Docker 19.03.2-ce
用clear tag创建容器然后只安装了nginx，运行一段时间后，再次访问页面显示500，抱歉，程序出现异常，但是容器内的nginx服务还是正常运行的，反代的其他容器服务都可以访问。

面板异常日志最后几行记录应该是这个
> [2019-10-08 19:03:23,544] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/usr/lib/python2.7/site-packages/flask_session/sessions.py", line 556, in save_session
    self.db.session.commit()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 498, in commit
    t[1].commit()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1716, in commit
    self._do_commit()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1747, in _do_commit
    self.connection._commit_impl()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 763, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 761, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 505, in do_commit
    dbapi_connection.commit()
OperationalError: (sqlite3.OperationalError) database or disk is full

记录的是磁盘空间不足，但/www还有76G可用，不知道是不是用了别的挂载点？
```
[root@archlinux wwwroot]# df -h  
Filesystem      Size  Used Avail Use% Mounted on
overlay          99G   18G   76G  19% /
tmpfs            64M     0   64M   0% /dev
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
shm              64M  444K   64M   1% /dev/shm
/dev/vda1        99G   18G   76G  19% /www
tmpfs           2.0G     0  2.0G   0% /proc/acpi
tmpfs           2.0G     0  2.0G   0% /proc/scsi
tmpfs           2.0G     0  2.0G   0% /sys/firmware
```

内存也是足够的
```
[root@archlinux wwwroot]# free -m
              total        used        free      shared  buff/cache   available
Mem:           3944        2696         124         594        1123         393
Swap:           999         728         271
```

**Comment by pch18** [comment]
感谢提供线索，这个问题发现有一段时间了，不太好再现。
在宿主机安装宝塔也发生过同样问题。只是概率较低。
我在一台4g的主机上也发生同样问题，但是另一台8g的主机就没出现过。

我会持续跟踪此问题，并且尽快给出解决办法。
目前可以不重启容器，在容器内部运行 `bt restart` 即可解决

**Comment by pch18** [comment]
大概知道原因了，修复中，
推测是容器内 /dev/shm 占满

**Comment by pch18** [comment]
请运行容器的时候加上以下参数
` --shm-size=1g `

**Comment by IllyaTheHath** [comment]
感谢，我去改一下试试

**Comment by IllyaTheHath** [comment]
现在运行了一天没有再出问题了，shm确实超出了docker的64m限制大小，1g目前是很够用了
